spring.application.name=telechurn-ai
server.port=5051
spring.datasource.url=jdbc:h2:mem:telechurndb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.thymeleaf.cache=false
spring.mvc.hiddenmethod.filter.enabled=true
model.directory=models
app.data-file=classpath:data/telco_churn.csv
spring.sql.init.mode=never
